server/db/models/index.js
server/db/models/product.js

product model

---

server/api/index.js
server/api/products.js
server/api/products.spec.js
server/db/db.js

created routes

---

package.json
server/db/db.js
server/db/models/index.js

got database to work

---

server/api/products.spec.js
server/api/users.spec.js
server/db/models/user.spec.js

I added a test spec file for routes and wrote tests for the GET product routes

tests working for product get  routesa

---

app/main.js
app/store.js
client/components/Product.js
client/components/Root.jsx
client/components/allProducts.js
client/index.js
client/store/index.js
client/store/productReducer.js
package.json

finished all products

---

.idea/workspace.xml
server/db/models/user.js

Made users model

---

client/components/SideBar.js
client/components/allProducts.js
script/seed.js
server/db/models/category.js
server/db/models/index.js
server/db/models/product.js
server/db/models/user.js

Just got sign in and sign up working and also log out, but did not get google to work yet (maybe it's not high priority)

User login signup

---

client/components/SideBar.js
client/components/allProducts.js
script/seed.js
server/db/models/category.js
server/db/models/index.js
server/db/models/product.js

category table done, sidebar taken out

---

client/components/Cart.js
client/components/index.js
client/components/navbar.js
client/index.js
client/routes.js
package-lock.json
package.json
public/style.css
webpack.config.js

shopping cart icon and route working

added shopping cart icon

---

client/components/Sidebar.js
client/components/allProducts.js
client/routes.js
client/store/categoriesReducer.js
client/store/index.js

categories rendering and reducer created

rendering all categories

---

client/components/AllProducts.js

fixed little bug

---

client/components/Cart.js
client/components/CartItem.js
client/routes.js
client/store/cartReducer.js
client/store/index.js
server/api/cart.js

got all the things working on seeing cart items

Connect back to front cart

---

client/components/Cart.js

cart page is working for users with no items in cart

---

client/components/Cart.js
client/routes.js

fixed login problems

---

script/seed.js

fixed seed file

---

server/db/models/order.js

fixed model

---

server/api/cart.js

Delete from cart backend route working

---

.idea/workspace.xml
client/components/AllOrders.js

Made AllOrder page nicer with regex

Made AllOrders page look a tad nicer with some regex

---

client/components/AddToCartButton.js
client/components/Cart.js
client/components/Category.js
client/components/DeleteCartItemButton.js
client/components/Order.js
client/components/Sidebar.js
client/store/cartReducer.js
server/api/cart.js
server/db/models/index.js

cleaned up most console.log statements (left a few notes)

---

client/components/AddToCartButton.js
client/components/Cart.js
client/components/Category.js
client/components/DeleteCartItemButton.js
client/components/Order.js
client/components/Sidebar.js
client/store/cartReducer.js
server/api/cart.js
server/api/products.js
server/db/models/index.js
server/db/models/product.js
server/db/models/user.js

Fixing price
